//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class referenciacliente
    {
        public int idreferenciacliente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string relacion { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string rfccliente { get; set; }
        public string horariodisponible { get; set; }
        public int cliente_idcliente { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
