//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCredito.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class politica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public politica()
        {
            this.solicitudhaspolitica = new HashSet<solicitudhaspolitica>();
        }
    
        public int idpolitica { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public System.DateTime vigencia { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitudhaspolitica> solicitudhaspolitica { get; set; }
    }
}
