//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCredito.model.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentosolicitud
    {
        public int iddocumentosolicitud { get; set; }
        public System.DateTime fecharegistro { get; set; }
        public byte[] archivobinario { get; set; }
        public int solicitudcredito_idsolicitudcredito { get; set; }
        public string extension { get; set; }
        public string nombrearchivo { get; set; }
        public int catalogodocumentos_numdocumento { get; set; }
    
        public virtual catalogodocumentos catalogodocumentos { get; set; }
        public virtual solicitudcredito solicitudcredito { get; set; }
    }
}
