//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCredito.model.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudhaspolitica
    {
        public int FK_solicitud { get; set; }
        public int FK_politica { get; set; }
        public Nullable<int> cumplida { get; set; }
        public Nullable<int> obligatoria { get; set; }
    
        public virtual politica politica { get; set; }
        public virtual solicitudcredito solicitudcredito { get; set; }
    }
}
