//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCredito.EntiteFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentacliente
    {
        public int idcuentacliente { get; set; }
        public string claveinterbancaria { get; set; }
        public int cliente_idcliente { get; set; }
        public int banco_idbanco { get; set; }
        public string tipotarjeta { get; set; }
        public string movilasociado { get; set; }
        public string numerotarjeta { get; set; }
    
        public virtual catalogobanco catalogobanco { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
