//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCredito.EntiteFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class datoscontacto
    {
        public Nullable<int> id_Cliente { get; set; }
        public int id_contacto { get; set; }
        public string correo { get; set; }
        public string celular { get; set; }
        public string telefono { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
