//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCredito.EntiteFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FOCUSEntities : DbContext
    {
        public FOCUSEntities()
            : base("name=FOCUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catalogobanco> catalogobanco { get; set; }
        public virtual DbSet<catalogodocumentos> catalogodocumentos { get; set; }
        public virtual DbSet<catalogostatus> catalogostatus { get; set; }
        public virtual DbSet<centrotrabajo> centrotrabajo { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<condiciones> condiciones { get; set; }
        public virtual DbSet<credito> credito { get; set; }
        public virtual DbSet<cuentacliente> cuentacliente { get; set; }
        public virtual DbSet<direccioncliente> direccioncliente { get; set; }
        public virtual DbSet<documentosolicitud> documentosolicitud { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<municipio> municipio { get; set; }
        public virtual DbSet<pagoamortizacion> pagoamortizacion { get; set; }
        public virtual DbSet<politica> politica { get; set; }
        public virtual DbSet<referenciacliente> referenciacliente { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<solicitudcredito> solicitudcredito { get; set; }
        public virtual DbSet<solicitudhaspolitica> solicitudhaspolitica { get; set; }
        public virtual DbSet<usuariosistema> usuariosistema { get; set; }
        public virtual DbSet<datoscontacto> datoscontacto { get; set; }
        public virtual DbSet<identificacion> identificacion { get; set; }
    }
}
