//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCredito.EntiteFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class identificacion
    {
        public int id_identificaion { get; set; }
        public string tipo { get; set; }
        public byte[] archivobinario { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cliente { get; set; }
    
        public virtual cliente cliente1 { get; set; }
    }
}
